#!/bin/bash

# set -e

launchctl unload "/Library/LaunchDaemons/ch.xxtou.procqueued.plist" > /dev/null 2>&1
launchctl remove com.xxtou.procqueued > /dev/null 2>&1

rm -f /usr/bin/1ferver/lib/exproc.so &> /dev/null
rm -f /var/mobile/Media/TouchSprite/lua/exproc.so &> /dev/null

mkdir -p /usr/bin/1ferver/lib &> /dev/null
mkdir -p /var/mobile/Media/TouchSprite/lua &> /dev/null

ln -s /usr/local/lib/libprocqueue.dylib /usr/bin/1ferver/lib/exproc.so &> /dev/null
ln -s /usr/local/lib/libprocqueue.dylib /var/mobile/Media/TouchSprite/lua/exproc.so &> /dev/null

sleep 1
launchctl load -w -F "/Library/LaunchDaemons/ch.xxtou.procqueued.plist" > /dev/null 2>&1

exit 0

