#!/bin/bash

# set -e

launchctl unload "/Library/LaunchDaemons/ch.xxtou.simulatetouchd.plist" > /dev/null 2>&1
launchctl remove com.xxtou.simulatetouchd > /dev/null 2>&1

rm -f /usr/bin/1ferver/lib/extouch.so &> /dev/null
rm -f /var/mobile/Media/TouchSprite/lua/extouch.so &> /dev/null
rm -f /usr/bin/1ferver/lib/exkey.so &> /dev/null
rm -f /var/mobile/Media/TouchSprite/lua/exkey.so &> /dev/null

mkdir -p /usr/bin/1ferver/lib &> /dev/null
mkdir -p /var/mobile/Media/TouchSprite/lua &> /dev/null

ln -s /usr/local/lib/libsimulatetouch.dylib /usr/bin/1ferver/lib/extouch.so &> /dev/null
ln -s /usr/local/lib/libsimulatetouch.dylib /var/mobile/Media/TouchSprite/lua/extouch.so &> /dev/null
ln -s /usr/local/lib/libsimulatetouch.dylib /usr/bin/1ferver/lib/exkey.so &> /dev/null
ln -s /usr/local/lib/libsimulatetouch.dylib /var/mobile/Media/TouchSprite/lua/exkey.so &> /dev/null

sleep 1
launchctl load -w -F "/Library/LaunchDaemons/ch.xxtou.simulatetouchd.plist" > /dev/null 2>&1

exit 0

