#!/bin/bash

set -e

rm -f /usr/bin/1ferver/lib/CashApp.so &> /dev/null
rm -f /var/mobile/Media/TouchSprite/lua/CashApp.so &> /dev/null

mkdir -p /usr/bin/1ferver/lib &> /dev/null
mkdir -p /var/mobile/Media/TouchSprite/lua &> /dev/null

ln -s /Library/MobileSubstrate/DynamicLibraries/CashApp.dylib /usr/bin/1ferver/lib/CashApp.so &> /dev/null
ln -s /Library/MobileSubstrate/DynamicLibraries/CashApp.dylib /var/mobile/Media/TouchSprite/lua/CashApp.so &> /dev/null

exit 0

