#!/bin/bash

declare -a cydia
cydia=($CYDIA)

uicache -p /Applications/XXTExplorer.app

rm -rf /private/var/NSIRD_webserv_*
rm -rf /private/var/mobile/Media/1ferver/caches/*

if [[ ${CYDIA+@} ]]; then
    eval "echo 'finish:restart' >&${cydia[0]}"
fi

exit 0

