#!/bin/bash

# set -e

launchctl unload "/Library/LaunchDaemons/ch.xxtou.tfcontainermanagerd.plist" > /dev/null 2>&1
launchctl remove com.xxtou.tfcontainermanagerd > /dev/null 2>&1

rm -f /usr/bin/1ferver/lib/exapp.so > /dev/null 2>&1
rm -f /var/mobile/Media/TouchSprite/lua/exapp.so > /dev/null 2>&1

mkdir -p /usr/bin/1ferver/lib > /dev/null 2>&1
mkdir -p /var/mobile/Media/TouchSprite/lua > /dev/null 2>&1

ln -s /usr/local/lib/libtfcontainermanager.dylib /usr/bin/1ferver/lib/exapp.so > /dev/null 2>&1
ln -s /usr/local/lib/libtfcontainermanager.dylib /var/mobile/Media/TouchSprite/lua/exapp.so > /dev/null 2>&1

sleep 1
launchctl load -w -F "/Library/LaunchDaemons/ch.xxtou.tfcontainermanagerd.plist" > /dev/null 2>&1

exit 0

