<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>lua</string>
		<string>p8</string>
		<string>rockspec</string>
		<string>snippet</string>
		<string>xui</string>
	</array>
	<key>firstLineMatch</key>
	<string>\A#!.*?\blua(\d+(\.\d+)?)?\b|\A--\s+-\*-\s*lua\s*-\*-</string>
	<key>keyEquivalent</key>
	<string>^~L</string>
	<key>repository</key>
	<dict>
		<key>escaped_char</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\[abfnrtvz\\&quot;&apos;\n]</string>
					<key>name</key>
					<string>constant.character.escape.lua</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\\d{1,3}</string>
					<key>name</key>
					<string>constant.character.escape.byte.lua</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\x[0-9A-Fa-f][0-9A-Fa-f]</string>
					<key>name</key>
					<string>constant.character.escape.byte.lua</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\u\{[0-9A-Fa-f]+\}</string>
					<key>name</key>
					<string>constant.character.escape.unicode.lua</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>invalid.illegal.character.escape.lua</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>uuid</key>
	<string>93E017CC-6F27-11D9-90EB-000D93589AF7</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>end</key>
			<string>\)</string>
			<key>begin</key>
			<string>\b((local\b)\s+)?(function)\s*(\s+[a-zA-Z_][a-zA-Z0-9_]*(\.[a-zA-Z_][a-zA-Z0-9_]*)*(:[a-zA-Z_][a-zA-Z0-9_]*)?\s*)?(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.lua</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.lua</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.lua</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.local.lua</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[a-zA-Z_][a-zA-Z0-9_]*</string>
					<key>name</key>
					<string>variable.parameter.function.lua</string>
				</dict>
			</array>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.lua</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.lua</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![\w\d.])0[xX][0-9A-Fa-f]+(?![pPeE.0-9])</string>
			<key>name</key>
			<string>constant.numeric.integer.hexadecimal.lua</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![\w\d.])0[xX][0-9A-Fa-f]+(\.[0-9A-Fa-f]+)?([eE]-?\d*)?([pP][-+]\d+)?</string>
			<key>name</key>
			<string>constant.numeric.float.hexadecimal.lua</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![\w\d.])\d+(?![pPeE.0-9])</string>
			<key>name</key>
			<string>constant.numeric.integer.lua</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![\w\d.])\d+(\.\d+)?([eE]-?\d*)?</string>
			<key>name</key>
			<string>constant.numeric.float.lua</string>
		</dict>
		<dict>
			<key>end</key>
			<string>&apos;</string>
			<key>begin</key>
			<string>&apos;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.lua</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped_char</string>
				</dict>
			</array>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.lua</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.lua</string>
		</dict>
		<dict>
			<key>end</key>
			<string>&quot;</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.lua</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped_char</string>
				</dict>
			</array>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.lua</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.lua</string>
		</dict>
		<dict>
			<key>end</key>
			<string>\]\1\]</string>
			<key>begin</key>
			<string>(?&lt;!--)\[(=*)\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.lua</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.lua</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.other.multiline.lua</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\A(#!).*$\n?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.lua</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.line.shebang.lua</string>
		</dict>
		<dict>
			<key>end</key>
			<string>\]\1\]</string>
			<key>begin</key>
			<string>--\[(=*)\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.lua</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.end.lua</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.lua</string>
		</dict>
		<dict>
			<key>end</key>
			<string>\n</string>
			<key>begin</key>
			<string>--</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.lua</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.line.double-dash.lua</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(goto)\s+([a-zA-Z_][a-zA-Z0-9_]*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.goto.lua</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.placeholder.lua</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(::)[a-zA-Z_][a-zA-Z0-9_]*(::)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.label.begin.lua</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.label.end.lua</string>
				</dict>
			</dict>
			<key>name</key>
			<string>constant.other.placeholder.lua</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(break|do|else|for|if|elseif|goto|return|then|repeat|while|until|end|function|local|in)\b</string>
			<key>name</key>
			<string>keyword.control.lua</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![^.]\.|:)\b(false|nil|true|_G|_VERSION|math\.(pi|huge))\b|(?&lt;![.])\.{3}(?!\.)</string>
			<key>name</key>
			<string>constant.language.lua</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![^.]\.|:)\b(self)\b</string>
			<key>name</key>
			<string>variable.language.self.lua</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![^.]\.|:)\b(assert|collectgarbage|dofile|error|getfenv|getmetatable|ipairs|loadfile|loadstring|module|next|pairs|pcall|print|rawequal|rawget|rawset|require|select|setfenv|setmetatable|tonumber|tostring|type|unpack|xpcall)\b(?=\s*(?:[({&quot;&apos;]|\[\[))</string>
			<key>name</key>
			<string>support.function.lua</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![^.]\.|:)\b(coroutine\.(create|resume|running|status|wrap|yield)|string\.(byte|char|dump|find|format|gmatch|gsub|len|lower|match|rep|reverse|sub|upper)|table\.(concat|insert|maxn|remove|sort)|math\.(abs|acos|asin|atan2?|ceil|cosh?|deg|exp|floor|fmod|frexp|ldexp|log|log10|max|min|modf|pow|rad|random|randomseed|sinh?|sqrt|tanh?)|io\.(close|flush|input|lines|open|output|popen|read|tmpfile|type|write)|os\.(clock|date|difftime|execute|exit|getenv|remove|rename|setlocale|time|tmpname)|package\.(cpath|loaded|loadlib|path|preload|seeall)|debug\.(debug|[gs]etfenv|[gs]ethook|getinfo|[gs]etlocal|[gs]etmetatable|getregistry|[gs]etupvalue|traceback))\b(?=\s*(?:[({&quot;&apos;]|\[\[))</string>
			<key>name</key>
			<string>support.function.library.lua</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(and|or|not)\b</string>
			<key>name</key>
			<string>keyword.operator.lua</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([a-zA-Z_][a-zA-Z0-9_]*)\b(?=\s*(?:[({&quot;&apos;]|\[\[))</string>
			<key>name</key>
			<string>support.function.any-method.lua</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=[^.]\.|:)\b([a-zA-Z_][a-zA-Z0-9_]*)</string>
			<key>name</key>
			<string>variable.other.lua</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|-|%|#|\*|\/|\^|==?|~=|&lt;=?|&gt;=?|(?&lt;!\.)\.{2}(?!\.)</string>
			<key>name</key>
			<string>keyword.operator.lua</string>
		</dict>
	</array>
	<key>comment</key>
	<string>Lua Syntax: version 0.8</string>
	<key>name</key>
	<string>Lua</string>
	<key>scopeName</key>
	<string>source.lua</string>
</dict>
</plist>
