#!/bin/bash

# set -e

rm -f /usr/bin/1ferver/lib/monkey.so > /dev/null 2>&1
rm -f /var/mobile/Media/TouchSprite/lua/monkey.so > /dev/null 2>&1
rm -f /usr/lib/libtampermonkey.dylib > /dev/null 2>&1

mkdir -p /usr/bin/1ferver/lib > /dev/null 2>&1
mkdir -p /var/mobile/Media/TouchSprite/lua > /dev/null 2>&1

ln -s /usr/local/xxtouch/lib/monkey.so /usr/bin/1ferver/lib/monkey.so > /dev/null 2>&1
ln -s /usr/local/xxtouch/lib/monkey.so /var/mobile/Media/TouchSprite/lua/monkey.so > /dev/null 2>&1
ln /usr/local/lib/libtampermonkey.dylib /usr/lib/libtampermonkey.dylib > /dev/null 2>&1

killall -9 webinspectord > /dev/null 2>&1

exit 0

